{% set name = "pygeoif" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeoif-{{ version }}.tar.gz
  sha256: cbbfc82ebdbd9f009a2243aa5d04423e5229bf913fc65fa5c87df60d9c94d77d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - typing-extensions

test:
  imports:
    - pygeoif
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cleder/pygeoif/
  summary: A basic implementation of the __geo_interface__
  license: LGPL-2.1-or-later
  license_file:
    - LICENSE.GPL
    - LICENSE.txt

extra:
  recipe-maintainers:
    - benjwadams
    - daf
    - kwilcox
    - lukecampbell
    - ocefpaf
