{% set name = "pygeoif" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygeoif-{{ version }}.tar.gz
  sha256: f27a6b6a1ecb87aeacc2b51bcc59ca79be70ed12a0104de8601478b213dd5d81

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - typing_extensions
    - python >=3.8
    - typing-extensions

test:
  imports:
    - pygeoif
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cleder/pygeoif/
  summary: A basic implementation of the __geo_interface__
  license: LGPL-2.1-or-later
  license_file:
    - LICENSE.GPL
    - LICENSE.txt

extra:
  recipe-maintainers:
    - benjwadams
    - daf
    - kwilcox
    - lukecampbell
    - ocefpaf
